global:
  datacenter: safecharge
  image: "consul:latest" # When using local REPO this should be changed
# Expose the Consul UI through this LoadBalancer
ui:
  service:
    type: "NodePort"
# Allow Consul to inject the Connect proxy into Kubernetes containers
connectInject:
  enabled: true
# Configure a Consul client on Kubernetes nodes. GRPC listener is required for Connect.
client:
  enabled: true
  grpc: true
# Minimal Consul configuration. Not suitable for production.
server:
  replicas: 2
  bootstrapExpect: 1
  disruptionBudget:
    enabled: true
    maxUnavailable: 1
# Sync Kubernetes and Consul services
syncCatalog:
  enabled: true

livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1